language: r
warnings_are_errors: true
sudo: required

r_build_args: '--compact-vignettes="gs+qpdf"'

addons:
  apt:
    packages:
        - libmagick++-dev
        - libgdal-dev
        - libudunits2-dev
        - saga